### PR TITLE
QA-1431: Script to render ConfigMap for MCTerra Component Version Identification.

### PR DESCRIPTION
**Pull request by ichengchang**
This script collects all currently available `MCTerra` Component Versions from `terra-helmfile`, organize them into standard reusable `ConfigMap` format. This enables `TestRunner` to dynamically retrieve the target component versions from different test environments for test results reporting for any kind of tests.

### CODE REVIEW

**Comment by emandakh** [comment]
A couple of comments, as we spoke in the meeting:
- chart version should be included as well, the combination of chart version + app version is required to define the unique state of a service
- look into using helm charts and go templates for the configmap templating, for example: https://github.com/broadinstitute/terra-helm/blob/master/charts/thurloe/templates/roleBinding.yaml

**Comment by ichengchang** [comment]
Chart versions have been added. Porting the shell script to GO templates will be tracked in QA Backlog as a separate ticket.

Initiated a Wiki page: [https://github.com/DataBiosphere/terra-test-runner/](https://github.com/DataBiosphere/terra-test-runner/wiki).

**Review by emandakh — APPROVED** [review]
Glad to see the env specific overrides and index testing!

**Review by marikomedlock — APPROVED** [review]
I think it would be helpful to include an example of when to call this script (e.g. in a GH action in the WSM repo). I understand this is follow-on work and not ready, yet. But in the meantime, could we add a README section about when we expect to use this script? Then we can go back later and link example code.

**Pull request merged**
