### PR TITLE
QA-1450: TestRunner Results BigQuery Schema including Component Version field in testRun table.

### PR DESCRIPTION
**Pull request by ichengchang**
This is the complete BigQuery Schema (in `JSON` format) for test results reporting.
The  `testRun` table now includes a component version field.

### CODE REVIEW

**Review by marikomedlock — COMMENTED** [review]
Are these files used in a script to create the BQ tables for uploading? I don't see them being used anywhere, so I'm not sure what the intent is here.

**Comment by ichengchang** [comment]
> Are these files used in a script to create the BQ tables for uploading? I don't see them being used anywhere, so I'm not sure what the intent is here.

Yes, the intention for these schema files is to automate the creation of the tables with a script. The script is not part of this ticket.

**Comment by marikomedlock** [comment]
> Yes, the intention for these schema files is to automate the creation of the tables with a script. The script is not part of this ticket.

Okay, my preference is not to put in un-used code. Is there a script you have been using to test these JSON files that you could include? For example, for the TDR Test Runner results, there is [this directory](https://github.com/DataBiosphere/jade-data-repo/tree/develop/datarepo-clienttests/tools/uploadResultsBQsetup) with a script and the JSON schema definitions. Can we do something similar here?

**Review by marikomedlock — APPROVED** [review]
LGTM. Can you also include a section in the README about what this script does and when to call it?

**Review by ungwudik — APPROVED** [review]

**Pull request merged**
